name: Build and Deploy Next.js App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run linting
        run: npm run lint

      - name: Run type checking
        run: npm run type-check

      - name: Build Next.js app
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: nextjs-build-${{ matrix.node-version }}
          path: out/
          retention-days: 7

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'


    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: nextjs-build-20.x
          path: out/

      - name: Deploy to GitHub Pages
        id: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: out

  # Alternative: Deploy to Vercel (uncomment if using Vercel)
  # deploy-vercel:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   if: github.ref == 'refs/heads/main' && github.event_name == 'push'
  #
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4
  #
  #     - name: Deploy to Vercel
  #       uses: amondnet/vercel-action@v25
  #       with:
  #         vercel-token: ${{ secrets.VERCEL_TOKEN }}
  #         vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
  #         vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
  #         vercel-args: '--prod'

  # Alternative: Deploy to custom server via SSH (uncomment if using custom server)
  # deploy-server:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   if: github.ref == 'refs/heads/main' && github.event_name == 'push'
  #
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4
  #
  #     - name: Download build artifacts
  #       uses: actions/download-artifact@v4
  #       with:
  #         name: nextjs-build-20.x
  #         path: .next/
  #
  #     - name: Deploy to Server
  #       env:
  #         SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  #         SERVER_USER: ${{ secrets.SERVER_USER }}
  #         SERVER_IP: ${{ secrets.SERVER_IP }}
  #         SERVER_PATH: ${{ secrets.SERVER_PATH }}
  #       run: |
  #         echo "$SSH_PRIVATE_KEY" > private_key.pem
  #         chmod 600 private_key.pem
  #         rsync -avz -e "ssh -i private_key.pem -o StrictHostKeyChecking=no" .next/ $SERVER_USER@$SERVER_IP:$SERVER_PATH
  #         ssh -i private_key.pem -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP << 'EOF'
  #           cd $SERVER_PATH
  #           npm install --production
  #           pm2 restart all
  #         EOF
